2023-04-24 02:44:45,891 - root - DEBUG - 127.0.0.1 - - [24/Apr/2023 02:44:45] "GET / HTTP/1.1" 200 -2023-04-24 03:24:23,399 - root - ERROR - type object 'QProcess' has no attribute 'Running'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 342, in create_server
    if broker_process.state() == QProcess.Running:
AttributeError: type object 'QProcess' has no attribute 'Running'
2023-04-24 03:59:41,699 - root - ERROR - [Errno 13] Permission denied: '/etc/mosquitto/mosquitto.conf'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 360, in create_server
    with open(conf_file_path, "w") as f:
PermissionError: [Errno 13] Permission denied: '/etc/mosquitto/mosquitto.conf'
2023-04-24 04:02:04,003 - root - ERROR - name 'ip_address' is not defined
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 354, in create_server
    os.system(f"pkexec echo 'listener {ip_address}:{port_number}' > /etc/mosquitto/mosquitto.conf")
NameError: name 'ip_address' is not defined
2023-04-24 04:06:34,953 - root - ERROR - 'PyQt6.QtCore.pyqtBoundSignal' object has no attribute 'start'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 359, in create_server
    self.broker_process.finished.start("mosquito",["-c","/etc/mosquitto/mosquitto.conf"])
AttributeError: 'PyQt6.QtCore.pyqtBoundSignal' object has no attribute 'start'
2023-04-24 04:14:58,473 - root - ERROR - module 'os' has no attribute 'getCwd'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 359, in create_server
    self.broker_process.start("mosquito",["-c",f"{os.getCwd()}/mosquitto.conf"])
AttributeError: module 'os' has no attribute 'getCwd'
2023-04-24 04:22:28,690 - root - ERROR - 'QLineEdit' object has no attribute 'settext'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 354, in create_server
    self.server_ip_input.settext("127.0.0.1")
AttributeError: 'QLineEdit' object has no attribute 'settext'
2023-04-24 04:24:29,054 - root - ERROR - 'NoneType' object has no attribute 'start'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 360, in create_server
    self.server_http_process.start("mosquitto", [ "-p", self.server_port_input.text()])
AttributeError: 'NoneType' object has no attribute 'start'
2023-04-25 06:32:13,894 - root - ERROR - [Errno 111] Connection refused
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 364, in create_server
    self.mqtt_server_client.connect(self.server_ip_input.text(),int(self.server_port_input.text()))
  File "/home/nikhil/.local/lib/python3.10/site-packages/paho/mqtt/client.py", line 914, in connect
    return self.reconnect()
  File "/home/nikhil/.local/lib/python3.10/site-packages/paho/mqtt/client.py", line 1044, in reconnect
    sock = self._create_socket_connection()
  File "/home/nikhil/.local/lib/python3.10/site-packages/paho/mqtt/client.py", line 3685, in _create_socket_connection
    return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
  File "/usr/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/usr/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
2023-04-25 06:36:48,876 - root - ERROR - [Errno 111] Connection refused
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 364, in create_server
    self.mqtt_server_client.connect("127.0.0.1",int(self.server_port_input.text()))
  File "/home/nikhil/.local/lib/python3.10/site-packages/paho/mqtt/client.py", line 914, in connect
    return self.reconnect()
  File "/home/nikhil/.local/lib/python3.10/site-packages/paho/mqtt/client.py", line 1044, in reconnect
    sock = self._create_socket_connection()
  File "/home/nikhil/.local/lib/python3.10/site-packages/paho/mqtt/client.py", line 3685, in _create_socket_connection
    return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
  File "/usr/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/usr/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
2023-04-25 06:47:11,152 - root - ERROR - [Errno 111] Connection refused
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 364, in create_server
    self.mqtt_server_client.connect("127.0.0.1",int(self.server_port_input.text()))
  File "/home/nikhil/.local/lib/python3.10/site-packages/paho/mqtt/client.py", line 914, in connect
    return self.reconnect()
  File "/home/nikhil/.local/lib/python3.10/site-packages/paho/mqtt/client.py", line 1044, in reconnect
    sock = self._create_socket_connection()
  File "/home/nikhil/.local/lib/python3.10/site-packages/paho/mqtt/client.py", line 3685, in _create_socket_connection
    return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
  File "/usr/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/usr/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
2023-04-25 06:53:42,566 - root - ERROR - [Errno 111] Connection refused
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 364, in create_server
    self.mqtt_server_client.connect("127.0.0.1",int(self.server_port_input.text()))
  File "/home/nikhil/.local/lib/python3.10/site-packages/paho/mqtt/client.py", line 914, in connect
    return self.reconnect()
  File "/home/nikhil/.local/lib/python3.10/site-packages/paho/mqtt/client.py", line 1044, in reconnect
    sock = self._create_socket_connection()
  File "/home/nikhil/.local/lib/python3.10/site-packages/paho/mqtt/client.py", line 3685, in _create_socket_connection
    return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
  File "/usr/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/usr/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
2023-04-25 06:57:17,138 - root - ERROR - [Errno 111] Connection refused
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 367, in create_server
    self.mqtt_server_client.connect("127.0.0.1",int(self.server_port_input.text()))
  File "/home/nikhil/.local/lib/python3.10/site-packages/paho/mqtt/client.py", line 914, in connect
    return self.reconnect()
  File "/home/nikhil/.local/lib/python3.10/site-packages/paho/mqtt/client.py", line 1044, in reconnect
    sock = self._create_socket_connection()
  File "/home/nikhil/.local/lib/python3.10/site-packages/paho/mqtt/client.py", line 3685, in _create_socket_connection
    return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
  File "/usr/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/usr/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
2023-04-25 06:59:50,017 - root - ERROR - 'MainWindow' object has no attribute 'broker_process'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 800, in closeEvent
    if self.broker_process is not None:
AttributeError: 'MainWindow' object has no attribute 'broker_process'
2023-04-25 07:04:42,047 - root - ERROR - [Errno 111] Connection refused
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 367, in create_server
    self.mqtt_server_client.connect("127.0.0.1",int(self.server_port_input.text()))
  File "/home/nikhil/.local/lib/python3.10/site-packages/paho/mqtt/client.py", line 914, in connect
    return self.reconnect()
  File "/home/nikhil/.local/lib/python3.10/site-packages/paho/mqtt/client.py", line 1044, in reconnect
    sock = self._create_socket_connection()
  File "/home/nikhil/.local/lib/python3.10/site-packages/paho/mqtt/client.py", line 3685, in _create_socket_connection
    return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
  File "/usr/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/usr/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
2023-04-25 07:23:52,591 - root - ERROR - 'MainWindow' object has no attribute 'broker_process'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 809, in closeEvent
    if self.broker_process is not None:
AttributeError: 'MainWindow' object has no attribute 'broker_process'
2023-04-25 07:26:05,577 - root - ERROR - 'MainWindow' object has no attribute 'tcp_server'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 382, in create_server
    elif self.tcp_server:
AttributeError: 'MainWindow' object has no attribute 'tcp_server'
2023-04-25 07:55:12,608 - root - ERROR - 'MainWindow' object has no attribute 'broker_process'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 820, in closeEvent
    self.broker_process.terminate()
AttributeError: 'MainWindow' object has no attribute 'broker_process'
2023-04-25 07:56:29,664 - root - ERROR - 'MainWindow' object has no attribute 'mqtt_server_client'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 383, in create_server
    self.mqtt_server_client.disconnect()
AttributeError: 'MainWindow' object has no attribute 'mqtt_server_client'
2023-04-25 08:07:53,393 - root - ERROR - 'MainWindow' object has no attribute 'broker_process'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 835, in closeEvent
    if self.broker_process is not None:
AttributeError: 'MainWindow' object has no attribute 'broker_process'
2023-04-25 08:11:21,577 - root - ERROR - wrapped C/C++ object of type QUdpSocket has been deleted
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 384, in create_server
    self.server_udp_socket.deleteLater()
RuntimeError: wrapped C/C++ object of type QUdpSocket has been deleted
2023-04-25 08:11:34,802 - root - ERROR - 'MainWindow' object has no attribute 'broker_process'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 835, in closeEvent
    if self.broker_process is not None:
AttributeError: 'MainWindow' object has no attribute 'broker_process'
2023-04-25 08:14:00,165 - root - ERROR - 'MainWindow' object has no attribute 'broker_process'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 838, in closeEvent
    if self.broker_process is not None:
AttributeError: 'MainWindow' object has no attribute 'broker_process'
2023-04-25 08:25:57,563 - root - ERROR - 'MainWindow' object has no attribute 'broker_process'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 838, in closeEvent
    if self.broker_process is not None:
AttributeError: 'MainWindow' object has no attribute 'broker_process'
2023-04-25 08:29:15,725 - root - ERROR - 'MainWindow' object has no attribute 'broker_process'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 838, in closeEvent
    if self.broker_process is not None:
AttributeError: 'MainWindow' object has no attribute 'broker_process'
2023-04-25 08:34:33,027 - root - ERROR - 'MainWindow' object has no attribute 'broker_process'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 845, in closeEvent
    if self.broker_process is not None:
AttributeError: 'MainWindow' object has no attribute 'broker_process'
2023-04-25 08:37:47,949 - root - ERROR - 'MainWindow' object has no attribute 'broker_process'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 850, in closeEvent
    if self.broker_process is not None:
AttributeError: 'MainWindow' object has no attribute 'broker_process'
2023-04-25 08:38:56,390 - root - ERROR - 'MainWindow' object has no attribute 'broker_process'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 852, in closeEvent
    if self.broker_process is not None:
AttributeError: 'MainWindow' object has no attribute 'broker_process'
2023-04-25 08:40:21,286 - root - ERROR - 'MainWindow' object has no attribute 'broker_process'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 855, in closeEvent
    if self.broker_process is not None:
AttributeError: 'MainWindow' object has no attribute 'broker_process'
2023-04-25 08:42:10,103 - root - ERROR - 'MainWindow' object has no attribute 'broker_process'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 855, in closeEvent
    if self.broker_process is not None:
AttributeError: 'MainWindow' object has no attribute 'broker_process'
2023-04-25 08:44:36,313 - root - ERROR - 'MainWindow' object has no attribute 'broker_process'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 856, in closeEvent
    if self.broker_process is not None:
AttributeError: 'MainWindow' object has no attribute 'broker_process'
2023-04-25 08:51:43,470 - root - ERROR - 'MainWindow' object has no attribute 'broker_process'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 855, in closeEvent
    if self.broker_process is not None:
AttributeError: 'MainWindow' object has no attribute 'broker_process'
2023-04-25 08:56:54,371 - root - ERROR - 'MainWindow' object has no attribute 'broker_process'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 863, in closeEvent
    if self.broker_process is not None:
AttributeError: 'MainWindow' object has no attribute 'broker_process'
2023-04-25 08:58:55,109 - root - ERROR - 'MainWindow' object has no attribute 'broker_process'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 863, in closeEvent
    if self.broker_process is not None:
AttributeError: 'MainWindow' object has no attribute 'broker_process'
2023-04-25 09:00:09,373 - root - ERROR - 'MainWindow' object has no attribute 'broker_process'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 864, in closeEvent
    if self.broker_process is not None:
AttributeError: 'MainWindow' object has no attribute 'broker_process'
2023-04-25 09:02:21,952 - root - ERROR - 'MainWindow' object has no attribute 'broker_process'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 865, in closeEvent
    if self.broker_process is not None:
AttributeError: 'MainWindow' object has no attribute 'broker_process'
2023-04-25 09:03:00,157 - root - ERROR - 'MainWindow' object has no attribute 'broker_process'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 864, in closeEvent
    if self.broker_process is not None:
AttributeError: 'MainWindow' object has no attribute 'broker_process'
2023-04-25 09:04:18,769 - root - ERROR - 'MainWindow' object has no attribute 'broker_process'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 865, in closeEvent
    if self.broker_process is not None:
AttributeError: 'MainWindow' object has no attribute 'broker_process'
2023-04-25 09:08:30,963 - root - ERROR - 'MainWindow' object has no attribute 'broker_process'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 867, in closeEvent
    if self.broker_process is not None:
AttributeError: 'MainWindow' object has no attribute 'broker_process'
2023-04-25 09:10:08,062 - root - ERROR - 'MainWindow' object has no attribute 'broker_process'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 877, in closeEvent
    if self.broker_process is not None:
AttributeError: 'MainWindow' object has no attribute 'broker_process'
2023-04-25 09:10:48,405 - root - ERROR - 'MainWindow' object has no attribute 'broker_process'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 877, in closeEvent
    if self.broker_process is not None:
AttributeError: 'MainWindow' object has no attribute 'broker_process'
2023-04-25 09:25:49,642 - root - ERROR - 'MainWindow' object has no attribute 'broker_process'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 889, in closeEvent
    if self.broker_process is not None:
AttributeError: 'MainWindow' object has no attribute 'broker_process'
2023-04-25 09:29:51,783 - root - ERROR - 'MainWindow' object has no attribute 'client_url'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 795, in client_send_data
    self.client_http_get_request()
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 876, in client_http_get_request
    http_client_url = f"http://{self.client_url}:{self.client_port}/"
AttributeError: 'MainWindow' object has no attribute 'client_url'
2023-04-25 09:31:45,055 - root - ERROR - 'MainWindow' object has no attribute 'broker_process'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 895, in closeEvent
    if self.server_http_process.state() != QProcess.ProcessState.NotRunning:
AttributeError: 'MainWindow' object has no attribute 'broker_process'
2023-04-25 09:32:17,033 - root - ERROR - 'MainWindow' object has no attribute 'client_url'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 795, in client_send_data
    self.client_http_get_request()
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 876, in client_http_get_request
    http_client_url = f"http://{self.client_url}:{self.client_port}/"
AttributeError: 'MainWindow' object has no attribute 'client_url'
2023-04-25 09:32:17,816 - root - ERROR - 'MainWindow' object has no attribute 'client_url'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 795, in client_send_data
    self.client_http_get_request()
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 876, in client_http_get_request
    http_client_url = f"http://{self.client_url}:{self.client_port}/"
AttributeError: 'MainWindow' object has no attribute 'client_url'
2023-04-25 09:32:28,087 - root - ERROR - 'MainWindow' object has no attribute 'broker_process'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 898, in closeEvent
    if self.broker_process is not None:
AttributeError: 'MainWindow' object has no attribute 'broker_process'
2023-04-25 09:36:55,925 - root - ERROR - 'MainWindow' object has no attribute 'client_url'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 796, in client_send_data
    self.client_http_get_request()
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 877, in client_http_get_request
    http_client_url = f"http://{self.client_url}:{self.client_port}/"
AttributeError: 'MainWindow' object has no attribute 'client_url'
2023-04-25 09:36:58,252 - root - ERROR - 'MainWindow' object has no attribute 'client_url'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 796, in client_send_data
    self.client_http_get_request()
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 877, in client_http_get_request
    http_client_url = f"http://{self.client_url}:{self.client_port}/"
AttributeError: 'MainWindow' object has no attribute 'client_url'
2023-04-25 09:37:08,290 - root - ERROR - 'MainWindow' object has no attribute 'broker_process'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 899, in closeEvent
    if self.broker_process is not None:
AttributeError: 'MainWindow' object has no attribute 'broker_process'
2023-04-25 09:39:32,166 - root - ERROR - 'MainWindow' object has no attribute 'client_url'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 797, in client_send_data
    self.client_http_get_request()
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 878, in client_http_get_request
    http_client_url = f"http://{self.client_url}:{self.client_port}/"
AttributeError: 'MainWindow' object has no attribute 'client_url'
2023-04-25 09:39:33,366 - root - ERROR - 'MainWindow' object has no attribute 'client_url'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 797, in client_send_data
    self.client_http_get_request()
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 878, in client_http_get_request
    http_client_url = f"http://{self.client_url}:{self.client_port}/"
AttributeError: 'MainWindow' object has no attribute 'client_url'
2023-04-25 09:39:34,022 - root - ERROR - 'MainWindow' object has no attribute 'client_url'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 797, in client_send_data
    self.client_http_get_request()
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 878, in client_http_get_request
    http_client_url = f"http://{self.client_url}:{self.client_port}/"
AttributeError: 'MainWindow' object has no attribute 'client_url'
2023-04-25 09:39:34,678 - root - ERROR - 'MainWindow' object has no attribute 'client_url'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 797, in client_send_data
    self.client_http_get_request()
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 878, in client_http_get_request
    http_client_url = f"http://{self.client_url}:{self.client_port}/"
AttributeError: 'MainWindow' object has no attribute 'client_url'
2023-04-25 09:39:35,182 - root - ERROR - 'MainWindow' object has no attribute 'client_url'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 797, in client_send_data
    self.client_http_get_request()
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 878, in client_http_get_request
    http_client_url = f"http://{self.client_url}:{self.client_port}/"
AttributeError: 'MainWindow' object has no attribute 'client_url'
2023-04-25 09:39:35,646 - root - ERROR - 'MainWindow' object has no attribute 'client_url'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 797, in client_send_data
    self.client_http_get_request()
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 878, in client_http_get_request
    http_client_url = f"http://{self.client_url}:{self.client_port}/"
AttributeError: 'MainWindow' object has no attribute 'client_url'
2023-04-25 09:39:36,102 - root - ERROR - 'MainWindow' object has no attribute 'client_url'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 797, in client_send_data
    self.client_http_get_request()
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 878, in client_http_get_request
    http_client_url = f"http://{self.client_url}:{self.client_port}/"
AttributeError: 'MainWindow' object has no attribute 'client_url'
2023-04-25 09:39:36,894 - root - ERROR - 'MainWindow' object has no attribute 'client_url'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 797, in client_send_data
    self.client_http_get_request()
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 878, in client_http_get_request
    http_client_url = f"http://{self.client_url}:{self.client_port}/"
AttributeError: 'MainWindow' object has no attribute 'client_url'
2023-04-25 09:39:37,318 - root - ERROR - 'MainWindow' object has no attribute 'client_url'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 797, in client_send_data
    self.client_http_get_request()
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 878, in client_http_get_request
    http_client_url = f"http://{self.client_url}:{self.client_port}/"
AttributeError: 'MainWindow' object has no attribute 'client_url'
2023-04-25 09:39:44,182 - root - ERROR - 'MainWindow' object has no attribute 'client_url'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 797, in client_send_data
    self.client_http_get_request()
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 878, in client_http_get_request
    http_client_url = f"http://{self.client_url}:{self.client_port}/"
AttributeError: 'MainWindow' object has no attribute 'client_url'
2023-04-25 09:40:13,470 - root - ERROR - 'MainWindow' object has no attribute 'client_url'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 797, in client_send_data
    self.client_http_get_request()
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 878, in client_http_get_request
    http_client_url = f"http://{self.client_url}:{self.client_port}/"
AttributeError: 'MainWindow' object has no attribute 'client_url'
2023-04-25 09:40:19,054 - root - ERROR - 'MainWindow' object has no attribute 'client_url'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 797, in client_send_data
    self.client_http_get_request()
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 878, in client_http_get_request
    http_client_url = f"http://{self.client_url}:{self.client_port}/"
AttributeError: 'MainWindow' object has no attribute 'client_url'
2023-04-25 09:40:19,831 - root - ERROR - 'MainWindow' object has no attribute 'client_url'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 797, in client_send_data
    self.client_http_get_request()
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 878, in client_http_get_request
    http_client_url = f"http://{self.client_url}:{self.client_port}/"
AttributeError: 'MainWindow' object has no attribute 'client_url'
2023-04-25 09:40:20,206 - root - ERROR - 'MainWindow' object has no attribute 'client_url'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 797, in client_send_data
    self.client_http_get_request()
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 878, in client_http_get_request
    http_client_url = f"http://{self.client_url}:{self.client_port}/"
AttributeError: 'MainWindow' object has no attribute 'client_url'
2023-04-25 09:40:20,478 - root - ERROR - 'MainWindow' object has no attribute 'client_url'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 797, in client_send_data
    self.client_http_get_request()
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 878, in client_http_get_request
    http_client_url = f"http://{self.client_url}:{self.client_port}/"
AttributeError: 'MainWindow' object has no attribute 'client_url'
2023-04-25 09:40:20,670 - root - ERROR - 'MainWindow' object has no attribute 'client_url'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 797, in client_send_data
    self.client_http_get_request()
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 878, in client_http_get_request
    http_client_url = f"http://{self.client_url}:{self.client_port}/"
AttributeError: 'MainWindow' object has no attribute 'client_url'
2023-04-25 09:40:20,878 - root - ERROR - 'MainWindow' object has no attribute 'client_url'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 797, in client_send_data
    self.client_http_get_request()
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 878, in client_http_get_request
    http_client_url = f"http://{self.client_url}:{self.client_port}/"
AttributeError: 'MainWindow' object has no attribute 'client_url'
2023-04-25 09:40:46,957 - root - ERROR - 'MainWindow' object has no attribute 'broker_process'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 900, in closeEvent
    if self.broker_process is not None:
AttributeError: 'MainWindow' object has no attribute 'broker_process'
2023-04-25 09:43:27,077 - root - ERROR - 'MainWindow' object has no attribute 'client_url'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 798, in client_send_data
    self.client_http_get_request()
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 879, in client_http_get_request
    http_client_url = f"http://{self.client_url}:{self.client_port}/"
AttributeError: 'MainWindow' object has no attribute 'client_url'
2023-04-25 09:43:27,825 - root - ERROR - 'MainWindow' object has no attribute 'client_url'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 798, in client_send_data
    self.client_http_get_request()
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 879, in client_http_get_request
    http_client_url = f"http://{self.client_url}:{self.client_port}/"
AttributeError: 'MainWindow' object has no attribute 'client_url'
2023-04-25 09:43:28,089 - root - ERROR - 'MainWindow' object has no attribute 'client_url'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 798, in client_send_data
    self.client_http_get_request()
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 879, in client_http_get_request
    http_client_url = f"http://{self.client_url}:{self.client_port}/"
AttributeError: 'MainWindow' object has no attribute 'client_url'
2023-04-25 09:43:28,281 - root - ERROR - 'MainWindow' object has no attribute 'client_url'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 798, in client_send_data
    self.client_http_get_request()
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 879, in client_http_get_request
    http_client_url = f"http://{self.client_url}:{self.client_port}/"
AttributeError: 'MainWindow' object has no attribute 'client_url'
2023-04-25 09:43:28,449 - root - ERROR - 'MainWindow' object has no attribute 'client_url'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 798, in client_send_data
    self.client_http_get_request()
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 879, in client_http_get_request
    http_client_url = f"http://{self.client_url}:{self.client_port}/"
AttributeError: 'MainWindow' object has no attribute 'client_url'
2023-04-25 09:44:03,496 - root - ERROR - 'MainWindow' object has no attribute 'broker_process'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 901, in closeEvent
    if self.broker_process is not None:
AttributeError: 'MainWindow' object has no attribute 'broker_process'
2023-04-25 09:45:59,217 - root - ERROR - 'MainWindow' object has no attribute 'broker_process'
Traceback (most recent call last):
  File "/home/nikhil/Desktop/Nikhil/wifi-server/my_ui.py", line 901, in closeEvent
    if self.broker_process is not None:
AttributeError: 'MainWindow' object has no attribute 'broker_process'
